### ISSUE TITLE
Request: Add "latest" tag to containers

### ISSUE THREAD

**Issue by eric-pierce** [jackyzy823/standardnotes-app-images#1]
I believe the only way to pull the latest container version is to manually specify the version. Assuming Github packages supports it, have you considered adding a latest tag?

Thanks for packaging this up - I was still running the 8 month old web container from the official docker hub. It's definitely an improvement to be running much closer to the latest version

**Comment by jackyzy823** [comment]
Basically, i don't like the concept of `latest` tag. It makes a compose environment not reproducible.

But if you like and need it , there it is. 

Wait for next week's build and hope it works.

**Comment by eric-pierce** [comment]
Thanks @jackyzy823 - I'll check it out when the next build goes out

**Comment by eric-pierce** [comment]
@jackyzy823 just used the latest tag and all worked well so far - I'll confirm it updates correctly next week as well
