### ISSUE TITLE
Web image

### ISSUE THREAD

**Issue by jonwsoto** [jackyzy823/standardnotes-app-images#4]
Hello, thanks for your work on providing an updated image to work with. I have it up and running and I am able to sign in with my server. The problem is no features are activated when I sign into your version of the webapp. 

I modified all necessary elements in the database per their documentation. When I sign in to an instance of their old web app it appears most note types do activate. 

Any ideas?

**Comment by jackyzy823** [comment]
Hello, thanks for pointing out. They changed some code , so the modification didn't apply. 

I update the modification and  add notes in README.

The next build will be at 20231107 04:00UTC, you could try the image after that time and test if the modification works.

**Comment by jonwsoto** [comment]
It works! This is amazing, you are the best!
