### ISSUE TITLE
[Question] Web app images still useful ?

### ISSUE THREAD

**Issue by jpbaril** [jackyzy823/standardnotes-app-images#8]
It looks like they restarted again creating docker images 7 months ago.
https://hub.docker.com/layers/standardnotes/web/9238759d38368fbad59db42100a6f35ebd8afd5c/images/sha256-5c91d4be24cef5f8f8e71dcd64126f43e132334ade84f5dd2685d0666df80437?context=explore

So is this one still useful ?

**Comment by jackyzy823** [comment]
Yep.

1) support your custom domain via env.
2) bypass client side restriction for premium features when self hosting.


And thanks for the hint . I could make my Dockerfile based on their image and make github action less work:)
